# Generated by Django 3.1.2 on 2020-10-27 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coincollector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('moto', models.TextField(max_length=250)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('datefound', models.DateField()),
                ('category', models.CharField(choices=[('M', 'Modern'), ('H', 'HISTORIC'), ('P', 'PRE-HISTORIC')], default='M', max_length=1)),
                ('metal', models.CharField(choices=[('G', 'GOLD'), ('S', 'SILVER'), ('B', 'BRONZE')], default='G', max_length=1)),
                ('coincollecor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.coincollector')),
            ],
        ),
    ]
