# Generated by Django 3.1.2 on 2020-10-28 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201027_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='coincollecor',
            new_name='coincollector',
        ),
    ]
