# Generated by Django 3.1.2 on 2020-10-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201028_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coinsymposium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='coincollector',
            name='symposiums',
            field=models.ManyToManyField(to='main_app.Coinsymposium'),
        ),
    ]
