# Generated by Django 3.1.2 on 2020-10-28 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201028_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinsymposium',
            name='description',
        ),
    ]
